### ISSUE TITLE
Resistor Value Confirmation

### ISSUE THREAD

**Issue by cap60552** [MagnusPer/Balboa-GS510SZ#20]
In your schematic you call for a 370ohm resistor as what ends up being R2 on the PCB.   I've been unable to locate a 370ohm size 0603 resistor.   Is this possibly supposed to be 470, or 330?  and if not, would either of those work in place of the 370?  I'm assuming the 470 would probably be ok since its current limiting on the opto-isolator, but I wanted to get confirmation.

**Comment by MagnusPer** [comment]
@cap60552 - There should be available 370 ohm 0602 size resistor, I just goggle it and found a number of suppliers! However a 470 ohm resistor should also work fine, have not tested it though!
