### ISSUE TITLE
HA HVAC control - unable to change Target Temperature

### ISSUE THREAD

**Issue by s1dave-web** [MagnusPer/Balboa-GS510SZ#26]
With a new D1 mini I now have a fully working setup with sensor and display data on my GS501SZ + 5 Button VL701S:
<img width="245" alt="Spa_Controls" src="https://github.com/user-attachments/assets/09cd8fc3-5a71-49c1-8a44-d0bd4f105123">

The only part not functioning is HVAC - so far I have managed to get it to have the correct current and target temperature by changing line 222:
deleted:
          hvac.setCurrentTargetTemperature(Balboa.waterTemperature);

added:
          hvac.setCurrentTemperature(Balboa.waterTemperature);
          hvac.setTargetTemperature(Balboa.setTemperature);

Ultimate goal would be to get temperature changes on the HVAC card to increase the setTemperature value.
<img width="407" alt="HVAC" src="https://github.com/user-attachments/assets/ec0addde-3fa9-4689-8a22-ffd3bed27bdb">

I have a feeling something with onTargetTemperatureCommand should be changing temps:
```
void onTargetTemperatureCommand(HANumeric temperature, HAHVAC* sender) {
    float temperatureFloat = temperature.toFloat();

    Serial.print("Target Temperature: ");
    Serial.println(temperatureFloat);

    Balboa.updateTemperature(temperatureFloat);

    sender->setTargetTemperature(temperature); // report target temperature back to the HA panel
}
```

But I am a bit stuck... hoping someone with ArduinoHA knowledge could help... @netmindz possibly?

**Comment by netmindz** [comment]
The changes look correct, if you logger is showing the right target value when you change, then it's an issue with the set temp call in the library

**Comment by s1dave-web** [comment]
Serial monitor shows nothing when changing the temp on the HVAC card

Using Balboa_GS_Read.ino sending case 8 and 9 work fine... so it would appear HA isn't sending command

I do see some MQTT messages that look like attempts to change target:
<img width="291" alt="mqtt" src="https://github.com/user-attachments/assets/5112bdca-59ee-4413-90c8-00e1a1e65cb4">

Is there a simpler way without using HVAC card that I can set the temperature to a specific value within HA? At the moment the only way would be to send Temp Up a certain amount of times.... possibly use some code from MQTT example?

**Comment by s1dave-web** [comment]
Is there a simpler way without using HVAC card that I can set the temperature to a specific value within HA? At the moment the only way would be to send Temp Up a certain amount of times.

**Comment by netmindz** [comment]
It's missing

hvac.onTargetTemperatureCommand(onTargetTemperatureCommand);

**Comment by s1dave-web** [comment]
That was it... so silly of me!

I am going to make a PR with a new file for 1 pump tubs because the new version of the current file has changed to switches which does not work for me as I need to be able to press pump1 twice to alternate speeds so button works best.

**Comment by s1dave-web** [comment]
That was it... so silly of me!

I am going to make a PR with a new file for 1 pump tubs because the new version of the current file has changed to switches which does not work for me as I need to be able to press pump1 twice to alternate speeds so button works best.

**Comment by netmindz** [comment]
Silly me more like to have missed that in my initial code :)
