### ISSUE TITLE
BOM list for PCB?

### ISSUE THREAD

**Issue by thoby1** [MagnusPer/Balboa-GS510SZ#5]
Very interesting project. Thought I would test this, but have limited electronics knowledge.
Could you attach a BOM list so that it would be easier to order all the necessary components for the PCB board?

**Comment by cbakkerprive** [comment]
Wow, cool! I too am definitely interested in the BOM list.

**Comment by MagnusPer** [comment]
I have been using this for a couple of months now and it works as I expected with my main purpose to heat the SPA during the cheapest hours.

The BOM list hopefully explained in the [Wiring](https://github.com/MagnusPer/Balboa-GS510SZ#wiring) section. What you need is the following:

3 pcs  - 1 kOhm resistor
2 pcs  - 2 kOhm resistor
1 pcs  - 220 Ohm resistor
1 pcs  - 370 ohm resistor
2 pcs  -  EL816 optocoupler 
1 pcs  - Wemos D1 mini 
1 pcs  - RJ45 cable  (Be aware the are different cables of crossed and straight wire configuration)
2 pcs  - RJ45 connectors (Optional)

You necessary not need to have RJ45 connectors, instead you can solder the wires directly to the components

**Comment by thoby1** [comment]
Cool to hear it works! The use case with turning the heater on and off during low and high prices was exactly what I had in mind.

When it comes to purchase of parts there seems to be so much extra specifications that makes it hard to choose. For resistors for example there are spec for Voltage and Watt. Take the 2kOhm for example, will this item work:
**NQ06W4F2001T5E**
https://jlcpcb.com/partdetail/1050181-NQ06W4F2001T5E/C965049

**Comment by MagnusPer** [comment]
I uploaded the BOM list to folder [..extras/PCB layout](https://github.com/MagnusPer/Balboa-GS510SZ/tree/main/extras/PCB%20layout) I used when I purchased the PCB, hope this helps

**Comment by cbakkerprive** [comment]
Thank you!
Can you also provide the CPL file so I can order assembled from JLCPCB?

**Comment by MagnusPer** [comment]
@cbakkerprive - Not sure what you mean with the CPL file but I guess its the [PickAndPlace](https://github.com/MagnusPer/Balboa-GS510SZ/blob/main/extras/PCB%20layout/PickAndPlace_PCB_Balboa-%20GS510SZ_2022-12-10.csv) file?

**Comment by cbakkerprive** [comment]
Thanks MagnusPer!
Indeed I did mean the PickAndPlace File.
As stated I try to order the assembled PCB from JLCPCB.
I did upload the 3 files to JLCPCB, but unfortunately after selecting the BOM and the PickAndPlace file (and select Next) I get the following error:

_Incorrect format
File parsing timeout. Please try again later.__

Not all SMD component I assume.

Thanks anyway.

**Comment by MagnusPer** [comment]
@cbakkerprive - I think it's better you try yourself to create the PCB in e.g. EasyEda with the help of the Gerber files provided. I remember I needed to replace and change the optocouplers component due to missing parts in the factory. When you succeed to place the order please help others here by attaching your PCB production files. In my order I exclude the Wemos D1 mini which I soldered myself.

If you have any questions I'm here to help the best I can!

**Comment by thoby1** [comment]
I havesuccessfuly completed a order at JLCPCB with the "BOM.xls" and "PickAndPlace_PCB_Balboa-GS510SZ_2022-12-10.csv" file. This issue can be colsed.
