### ISSUE TITLE
Compability with GS501Z and VL200?

### ISSUE THREAD

**Issue by richardtjena** [MagnusPer/Balboa-GS510SZ#7]
Hi!

I have a Balboa GS501Z-control system with VL200 duplex display which uses RJ45 but only have four buttons.

Do we know if the data protocol is the same regardless if the display is a Duplex- (GS5xxZ), Standard- (GS5xxSZ), or Deluxepanel (GS5xxDZ-unit)?

BR

**Comment by MagnusPer** [comment]
@richardtjena  - Welcome in here to this repository!

There is another guy that has tried this for the GS500Z with the VL200 panel. The feedback I got was that is not works as expected. He is however trying to reuse and explore himself and trying to figure out the specific logic for that system.

**Comment by MagnusPer** [comment]
Closing this issue since this repository does not support Balboa GS501Z-control system with VL200 panel

**Comment by richardtjena** [comment]
@MagnusPer was it a user with a public repo? Any chance you can point me to his direction.

I also thought about flipping the J12 jumper in the control unit but don't know if it would have any effect without changing the ROM.

**Comment by MagnusPer** [comment]
@richardtjena - He does not have any public repo for his development. If you give me your mail address I can send an message to him and tell that you want to get in contact with him.

**Comment by StarkJohan** [comment]
I have the same setup and the protocols must be very similar. To avoid doing the work someone else already has done, please put me in contact with anyone that might help: johan@punktvvv.se

**Comment by netmindz** [comment]
The way to know about compatibility is to think about the fact we are emulating a panel, so if you look at which official panels are compatible with which controllers you know that they must use the same communication

**Comment by StarkJohan** [comment]
I'm using the VL240 panel and the protocol is indeed similar but there's a few big differences. I've outlined them in another issue.
In short it will not be possible to use this repo or the hardware without rather big changes.
