### ISSUE TITLE
how to determine if set temperature is displayed vs current water temperature?

### ISSUE THREAD

**Issue by techoguy** [MagnusPer/Balboa-GS510SZ#9]
Hi @MagnusPer I'm reading over the code to see if I can start from your code or if it'll be easier to start from scratch. Curious, on your display, when you press up or down to change the temperature and the display temporarily displays the set temperature vs the current water temperature, how does the ESP device know which temperature is displayed? On my spa, there appears to be no pattern or indicator in the messages to the control panel when the set temperature is displayed vs the current temperature which means I can't really tell which temperature is displayed unless I also have the button signals as inputs to know someone at the panel is changing the set temperature. curious how you're dealing with this. 

Thanks!

**Comment by MagnusPer** [comment]
Hi,
There is a trigger `displayButton` when the up/down button is pressed on the display. By this I can understand if it’s the water temperature or set temperature that is shown.

**Comment by techoguy** [comment]
Thank you! My spa doesn't appear to provide any sign of when the display is showing water temperature vs set temperature 😫. So I might have to have the button signal as an input and output.
